<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <nav>
            <a href="index.php">Accueil</a>
            <a href="experiences.php">Expériences</a>
            <a href="realisations.php">Réalisations</a>
            <a href="contact.php">Contact</a>
        </nav>
    </header>
    <main>
        Page contact
        <form action="manager/recupFormContact.php" method="post">

            <input type="text" name="txtNom" placeholder="Nom"><br>
            <input type="text" name="txtEmail" placeholder="Email"><br>
            <textarea name="txtMessage" placeholder="Message"></textarea><br><br>
            <input type="submit" value="Envoyer">

        </form>
    </main>
    <footer>
    </footer>
</body>
</html>