<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <nav>
            <a href="index.php">Accueil</a>
            <a href="experiences.php">Expériences</a>
            <a href="realisations.php">Réalisations</a>
            <a href="contact.php">Contact</a>
        </nav>
    </header>
    <main>
        Page expériences
        <table>
            <?php foreach($experiences as $experience) :?>
            <tr>
                <td><?= $experience->getTitre() ?></td>
            </tr>
            <?php endforeach ?>
        </table>
    </main>
    <footer>
    </footer>
</body>
</html>